dist: trusty
language: cpp

matrix:
  include:
  - os: linux
   
    env:
        - CMAKE_VERSION="3.8"
        - CMAKE_GENERATOR="Ninja"

script:
  - CXX=/usr/bin/g++-10 CC=/usr/bin/gcc-10 cmake .
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D WARNINGS_AS_ERRORS:BOOL=FALSE ../
  - cmake --build . -- -j2

