language: cpp

install:
  - python3 -m pip install --upgrade pip setuptools
  - pip install --upgrade cmake
  - cmake --version
  - clang --version

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - BADGE=Ubuntu_18.04
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
            - python3-pip
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
#    - os: linux
#      dist: bionic
#      compiler: clang
#      env:
#        - CLANG_VER="12"
#        - MATRIX_EVAL="CC=clang-${CLANG_VER} && CXX=clang++-${CLANG_VER}"
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main'
#              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
#          packages: 
#            - python3-pip
#            - clang-12
    - os: osx
      compiler: gcc
      osx_image: xcode12.4
      env:
        - BADGE=OSX
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
    - os: osx
      compiler: clang
      osx_image: xcode12.4
      env:
        - CXX=clang++
        - CXXSTD=-std=c++20
        - MATRIX_EVAL=""

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE ../
  - cmake --build . -- -j2



