dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-10
        - g++-10

script:
  - CXX=/usr/bin/g++-10 CC=/usr/bin/gcc-10 cmake .
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D WARNINGS_AS_ERRORS:BOOL=FALSE ../
  - cmake --build . -- -j2

