dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-9
            - g++-9
    compiler: gcc
    env:
        - CMAKE_VERSION="3.8"
        - CMAKE_GENERATOR="Ninja"
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D WARNINGS_AS_ERRORS:BOOL=FALSE ../
  - cmake --build . -- -j2

