image:
  - Visual Studio 2019
clone_folder: c:\project\source

install:
  - choco install codecov

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\project\source -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Debug"

    cmake --build . --config "Debug"

    dir

- codecov -f coverage.xml --root %APPVEYOR_BUILD_FOLDER%

test_script:
- '%APPVEYOR_BUILD_FOLDER%\build\RawBufferTests\RawBufferTests.exe'