image:
  - Visual Studio 2019
clone_folder: c:\project\source

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\project\source -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Debug"

    cmake --build . --config "Debug"

test_script:
- cmd: ctest -C Debug