image:
  - Visual Studio 2019
clone_folder: c:\project\source

build_script:
- cmd: >-
    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING="Debug"
    cmake --build . --config "Debug"